[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Jay Vana <jaysvana@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
structopt = "*"

[dev-dependencies]
anyhow = "*"
structopt = "*"
thiserror = "*"
